### ISSUE TITLE
Problem with godmode on spigot 1.12.2 and old armor strenght.

### ISSUE THREAD

**Issue by pjorun** [kernitus/BukkitOldCombatMechanics#589] opened 2022-01-24 15:32 UTC
* Server Version: 
* spigot/paper 1.12.2

* OldCombatMechanics version: 
* 1.10.0

* Server Log File: 
* no error

* OldCombatMechanics config file: 
* old-armour-strength: true

### To Reproduce
1.  diamond armor with protection 5
2. diamond sword with sharpness 5
3. enchanted apple

### Actual Behaviour
You do not get any damage. god mode on.

**Comment by kernitus** [comment] 2022-12-23 12:31
@pjorun please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:07
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:07 UTC
Labels: user vanished, awaiting testing
