### ISSUE TITLE
1.18 not supported 

### ISSUE THREAD

**Issue by GAMERFORCE99** [kernitus/BukkitOldCombatMechanics#599] opened 2022-03-13 16:43 UTC
when will you add 1.18 support? this is an amizing plugin and its just what i need

**Comment by MrDisastrous** [comment] 2022-03-13 23:30
The plugin supports 1.18 but you need to disable certain features (do not remember which) inorder to fix some compatibility issues.

**Comment by detobel36** [comment] 2022-03-14 10:16
Duplicated with https://github.com/kernitus/BukkitOldCombatMechanics/issues/598 and https://github.com/kernitus/BukkitOldCombatMechanics/issues/596

**Comment by GAMERFORCE99** [comment] 2022-03-14 12:02
> The plugin supports 1.18 but you need to disable certain features (do not remember which) inorder to fix some compatibility issues.
could please check and tell me what features do i need to disable?

**Comment by Drc-DEV** [comment] 2022-03-17 00:38
`[OldCombatMechanics] Error reloading module 'Disable Player Collisions'
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "method" is null
        at kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.invokeMethod(Reflector.java:101) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$ScoreboardTeamWither.build(V17TeamPacket.java:198) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.lambda$setCollisionRule$4(V17TeamPacket.java:127) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.getUnchecked(Reflector.java:220) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.setCollisionRule(V17TeamPacket.java:112) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.createTeamPacket(V17TeamPacket.java:150) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket.create(V17TeamPacket.java:51) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.packet.team.TeamPacket.create(TeamPacket.java:55) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.teams.TeamUtils.craftTeamCreatePacket(TeamUtils.java:37) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.createAndSendNewTeam(ModulePlayerCollisions.java:104) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.createOrUpdateTeam(ModulePlayerCollisions.java:91) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.reload(ModulePlayerCollisions.java:115) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.utilities.Config.lambda$reload$0(Config.java:81) ~[OldCombatMechanics-1.10.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at kernitus.plugin.OldCombatMechanics.utilities.Config.reload(Config.java:79) ~[OldCombatMechanics-1.10.0.jar:?]
        at kernitus.plugin.OldCombatMechanics.OCMCommandHandler.onCommand(OCMCommandHandler.java:60) ~[OldCombatMechanics-1.10.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-252]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

> The plugin supports 1.18 but you need to disable certain features (do not remember which) inorder to fix some compatibility issues.

**Comment by kernitus** [comment] 2022-03-17 20:28
Duplicate of #601

**Closed by kernitus** 2022-03-17 20:28 UTC
Labels: enhancement
