### ISSUE TITLE
Old clients can't join on PaperSpigot 1.15.2 if disable-player-collisions is true

### ISSUE THREAD

**Issue by camdenorrb** [kernitus/BukkitOldCombatMechanics#403] opened 2020-06-09 03:28 UTC
We wanted to disable collisions so we set disable-player-collisions to true, it ended up making majority of players unable to join. Mainly ones under 1.15.2

## Information
* Server Version:  Paper 1.15.2 Build # 343

* OldCombatMechanics version: 1.8.0

* Server Log File: https://pastebin.com/9y7i6Ec0

* OldCombatMechanics config file: https://pastebin.com/9y7i6Ec0

## Problem Description

Players running below server version can't join if disable-player-collisions is true

 
### To Reproduce
1. Install combat mechanics
2. Set disable-player-collisions to true
3. Watch as your playerbase slowly dies

### Expected Behaviour
Player base not to die

### Actual Behaviour

Player base dies :(

**Comment by kernitus** [comment] 2020-06-16 12:28
I don't see anything in the server log that points to this being and OCM issue, which makes me think it could be a conflict between plugins. Have you tried disabling some of the other plugins while `disable-player-collisions` is on?

**Comment by LeehamElectronics** [comment] 2020-06-30 02:27
I’m having this issue too and I have verified that it is OCM causing it. Players are kicked when joining a mini game with a score board error, it does not happen when disable player collisions is set to false in the OCM config, also disabling player collisions with OCM or the paper mc config don’t seem to work at all, any ideas?

**Comment by LeehamElectronics** [comment] 2020-07-10 23:42
Any ETA on when this will be fixed? My players are getting really annoyed at players pushing each other off bridges while spectating.
Thanks

**Comment by kernitus** [comment] 2020-07-12 11:08
> Any ETA on when this will be fixed? My players are getting really annoyed at players pushing each other off bridges while spectating.
> Thanks

Please don't ask for ETAs on a free and open source project, if the issue is so urgent you can submit a fix yourself.

Other than that, in order to fix a bug we must first know what is causing it. The server log @camdenorrb provided doesn't seem to show any useful error, so if you could provide yours when the issue occurs we might get somewhere.
Also, it seems this may be a conflict with another plugin, are you using any other plugin that modifies the scoreboard in any way?

**Comment by I-Al-Istannen** [comment] 2020-08-08 08:34
I can not reproduce this error. Knowing the exact scoreboard configuration would help, i.e. what plugin sets the scoreboard and what it is set to.

**Comment by kernitus** [comment] 2020-10-03 15:11
@camdenorrb @LeehamElectronics could you please try the [test version](https://ci.rayzr.dev/job/OldCombatMechanics/46/) with the new patch? We think it might fix this issue.

**Closed** 2020-10-24 14:55 UTC
Labels: awaiting testing, bug, user vanished

**Comment by LeehamElectronics** [comment] 2021-11-26 00:39
Coming back to my first issue on GitHub, well this is embarrassing. iirc this issue had nothing to do with OCM, it was simply a configuration option in the [TAB ](https://github.com/NEZNAMY/TAB)plugin by NEZNAMY. Sorry for wasting your time.
