### ISSUE TITLE
Gap glitch

### ISSUE THREAD

**Issue by AstonicPI** [kernitus/BukkitOldCombatMechanics#519] opened 2021-05-15 20:28 UTC
## Information

* Server Version: PaperMC 1.12.2

* OldCombatMechanics version: latest (just downloaded it)

* Server Log File: [latest (7).log](https://github.com/kernitus/BukkitOldCombatMechanics/files/6488157/latest.7.log)

* OldCombatMechanics config file: https://paste.helpch.at/feleratiqo.bash

## Problem Description

Ok so, i updated the plugin to lastest version and one player started seeing this weird bug, so when he eats 1 god apple he loses 2 for some reason...

 
### To Reproduce
1. Eat 1 god apple
2.
3.

### Expected Behaviour
Lose 1 gapple instead of 2
### Actual Behaviour

Insead of losing 1 gap you lose 2

https://youtu.be/1RMBpAAvdaU

**Comment by AstonicPI** [comment] 2021-05-16 16:45
also theres a problem with gap animation reset on hit, would be awesome if you fix that :)

**Comment by kernitus** [comment] 2021-06-02 13:25
Duplicate of #500

**Closed by kernitus** 2021-06-02 13:25 UTC
