### ISSUE TITLE
OldCombatMechanics Weird Logs

### ISSUE THREAD

**Issue by Redwolf223** [kernitus/BukkitOldCombatMechanics#434] opened 2020-07-26 20:50 UTC
Hi i'm having some weird logs with oldcombatmechanics

My server version is 1.16 and i'm using YAPFA.

https://pastebin.com/7bdLteU1

These are the logs, let me know if you need any more infos.

**Comment by Rayzr522** [comment] 2020-07-27 19:22
@Redwolf223 looks like it may be related to (and actually an extension of) #425 -- but just to confirm, could you try out the [latest dev build (40) from my build server](https://ci.rayzr.dev/job/OldCombatMechanics/40/)?

also, have you been able to determine what it is that causes this error? hitting a player, hitting a particular kind of mob, something like that? kinda hard to reproduce from just the errors

**Comment by Rayzr522** [comment] 2020-08-07 06:52
i'm closing this as a duplicate of #425, and will continue the investigation of the error in that issue. if you have anything else to add, please add it there.

**Closed by Rayzr522** 2020-08-07 06:52 UTC
Labels: not enough info
