### ISSUE TITLE
I have a error log [Viaversion]

### ISSUE THREAD

**Issue by ReflexShow** [kernitus/BukkitOldCombatMechanics#445] opened 2020-08-06 14:13 UTC
* Server Version:  spigot 1.12.2 (via version)
* OldCombatMechanics version:  1.8.1
* Server Log File: https://hastebin.com/zucaxijofe.md
* OldCombatMechanics config file: https://hastebin.com/efitokimin.bash

Annoying error in log
```
[15:08:01] [Server thread/INFO]: ---------------------------
[15:08:01] [Server thread/INFO]: [OldCombatMechanics] Enabling OldCombatMechanics v1.8.1
[15:08:01] [Server thread/ERROR]: Error occurred while enabling OldCombatMechanics v1.8.1 (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
	at kernitus.plugin.OldCombatMechanics.hooks.PlaceholderAPIHook.init(PlaceholderAPIHook.java:13) ~[?:?]
	at kernitus.plugin.OldCombatMechanics.OCMMain.lambda$onEnable$0(OCMMain.java:61) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251]
	at kernitus.plugin.OldCombatMechanics.OCMMain.onEnable(OCMMain.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[15:08:01] [Server thread/INFO]: [CustomDrops] Enabling CustomDrops v3.1.4
[15:08:02] [Server thread/INFO]: [EternalOre] Enabling EternalOre v1.2.1
[15:08:02] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v3.0.1
[15:08:02] [Server thread/INFO]: [Wild] Enabling Wild v3.17.0
[15:08:02] [Server thread/INFO]: [0;37;22m-----------------------------------------------[m
```

**Comment by Rayzr522** [comment] 2020-08-06 21:08
duplicate of #437, see [this comment](https://github.com/kernitus/BukkitOldCombatMechanics/issues/437#issuecomment-669449688) for a dev build that should fix the error

**Closed by Rayzr522** 2020-08-06 21:08 UTC
