### ISSUE TITLE
Overpowered Enchantment Conflicts

### ISSUE THREAD

**Issue by Jeklund6** [kernitus/BukkitOldCombatMechanics#614] opened 2022-06-23 04:55 UTC
Edit: Very similar problems to issues #499, #560, and #589 hopefully I provided helpful information.

**Server Version: Paper 1.12.2**

I'm trying to create an OP Factions server with 1.8 style combat and OP enchants. Ex. (protection.0-100) (sharpness.0-50). 

While using this plugin once you have **x>=protection.5** you take negative damage from anything above **+4 Attack Damage.**

**Now this is when default is set _"old_armor_strength = true"_**

Screenshots below if they can possibly provide some explanation that I don't understand.
Images 1, 1.a, 2, 2.a have  **_"old_armor_strength = true"_** See config.yml: https://mcpaste.io/599ab873d279fbe8

**IMAGE 1: Attacker using sharpness.50 sword.**
![image](https://user-images.githubusercontent.com/34612810/175205718-a7c59769-3902-41bb-b71b-8c4e7d304b75.png)
**IMAGE 1.a: Defender wearing protection.5**
![image](https://user-images.githubusercontent.com/34612810/175205818-c692ca13-77fb-49cb-885d-fcc07eb22875.png)

**IMAGE 2: Attacker using wooden sword**
![image](https://user-images.githubusercontent.com/34612810/175206777-82925979-1e4b-4339-b6d6-4e3f20be5c8c.png)
**IMAGE 2.a: Defender wearing protection.5**
![image](https://user-images.githubusercontent.com/34612810/175206641-3d34d2b5-a106-4d5d-a694-960c044132df.png)

**Below is a somewhat separate issue from above**
------------------------------------------------------------
**I dont know if this is caused by the plugin or this is Minecraft but I thought I'd include it**
Troubleshooting the issues I tried setting it to false. Everything worked perfectly when _"old_armor_strength = false"_. Damage worked perfectly, but a different problem occurred; the difference in protection. Any **x>=protection.5 isn't more effective** _Ex. if I enchant something as **protection.100** it's no different than **protection.5** (same with durability)_
Images 3, 3.a, 4, 4.a have **_"old_armor_strength = false"_** See config.yml: https://mcpaste.io/ae4b7d15c9b2861e

**IMAGE 3: Attacker using sharpness.50 sword**
![image](https://user-images.githubusercontent.com/34612810/175210058-0c74cd40-bdf1-4d64-8bbb-48000c2412e2.png)
**IMAGE 3.a: Defender wearing protection.5** (Armor Strength not showing here because I set it to false I'm assuming) 
![image](https://user-images.githubusercontent.com/34612810/175210767-985f72a0-5d46-4676-88ee-293b763f73e9.png)

**IMAGE 4: Attacker using sharpness.50 sword**
![image](https://user-images.githubusercontent.com/34612810/175211076-1687ce81-849c-4e4f-9c32-fa0050861664.png)
**IMAGE 4.a: Defender wearing protection.100** (Armor Strength not showing here because I set it to false I'm assuming) 
![image](https://user-images.githubusercontent.com/34612810/175211533-9eb65d38-0040-4ce6-a13f-9297b61e0da8.png)

_As you can see, there was no difference in damage taken between **protection.5** and **protection.100**_

**Comment by kernitus** [comment] 2022-07-02 12:40
Thank you for actually providing some data, I will now have to do a lot of investigating and testing to figure out where the problem lies.

**Comment by Jeklund6** [comment] 2022-07-03 01:16
I've done some extra research after posting this which might help you or save time.

**The problem is Minecraft's EPF cap or (reaching 100% protection)** on armor/protection enchantments. _EPF cap is reached when wearing protection 5 diamond armor._

When **(EPF cap is reached)** and **(old_armor_strength = true)** then, you CAN'T take damage **because you're at 100% protection.**

When **(EPF cap is reached)** and **(old_armor_strength = false)** then, you CAN take damage, but the **damage you take doesn't decrease as protection level increases.**

**To fix**: I imagine it has to do with overriding Minecraft's default EPF cap/values, but that sounds like it would bring a host of other coding issues like making an entirely new EPF curve or dataset.

But, that's why I just look for plugins and not create them, hope this helps lol.

**Comment by kernitus** [comment] 2022-07-22 11:32
Thanks for providing such detailed information, I will be looking at this shortly. Would you be available to perform some testing if I managed to fix the issue?

**Comment by Jeklund6** [comment] 2022-07-22 20:13
Yeah I could do that.

**Comment by Jeklund6** [comment] 2022-08-29 12:48
Any update on this yet?

**Comment by kernitus** [comment] 2022-09-16 17:20
I am currently rewriting most of the damage calculation system. It requires a lot of testing to make sure it is actually accurate.

**Comment by kernitus** [comment] 2022-12-23 12:30
@Jeklund6 please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:06
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:06 UTC
Labels: bug, user vanished, awaiting testing

**Comment by Jeklund6** [comment] 2024-09-03 02:55
@kernitus I wanted to try making a server again and test your plugin, the problem I had persists. However I didn't feel like the need to respond because I started to get the feeling it wasn't your plugins fault it's just how the Minecraft EPF curve works and I don't know how to resolve that.
