### ISSUE TITLE
Attack frequency on 1.10.0

### ISSUE THREAD

**Issue by KrusteF** [kernitus/BukkitOldCombatMechanics#590] opened 2022-01-25 10:53 UTC
* Server Version: Paper 1.12.2

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/dQ2Cp2jX

* OldCombatMechanics config file: https://pastebin.com/DTy63wa6

https://prnt.sc/26j1s44

## Problem Description
For the past 2 months I've been trying to fix a bug (thinking it's from my plugin), but today i noticed when i change the version to 1.9.0 (OCM) that this bugs gets fixed:

The attack frequency does not work properly on 1.10.0 (OCM), meaning the player / mob can hit the player 10+ times per second, video:
https://youtu.be/kDEMSaP4HFs

You can clearly see that when the version is 1.10.0 the SLIME is attacking more then 1 or 2 times per second, but when the version is 1.9.0 he barely attacks

 
### To Reproduce
1. Install 1.10.0 (OCM) version
2. Try getting attacked by a mob
3. Install 1.9.0 (OCM) version
4. Try getting attacked by a mob again

### Expected Behaviour
As shown in the video, expected behaviour is to not being attacked 10+ times per second

### Actual Behaviour
Every mob attacks more then once per second.

**Comment by amarcais53** [comment] 2022-02-04 19:12
oh sorry for the mention , i also have this bug

**Comment by kernitus** [comment] 2022-12-23 12:31
@HamtaBot @KrusteF please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:07
Closing due to rewrite of all damage calculation code. Please contribute debug logs to issue #636 if you think the problem is still present.

**Closed by kernitus** 2023-02-01 13:07 UTC
Labels: user vanished, awaiting testing
