### ISSUE TITLE
No damage with weakness potion

### ISSUE THREAD

**Issue by ludgart** [kernitus/BukkitOldCombatMechanics#524] opened 2021-05-18 21:01 UTC
## Information

* Server Version: Paper 1.16.5-629

* OldCombatMechanics version: 1.9.0

* Server Log File: /

* OldCombatMechanics config file: https://pastebin.com/XjYfH3h3

### To Reproduce
1. Use the config above
2. Change the weakness modifier to 0.1 or something else ( doesnt matter ). Or turn off the module
3. Try to hit a player with your hand / wooden sword.

### Expected Behaviour
Reduced damage to the player

### Actual Behaviour

No damage to the player

**Comment by kernitus** [comment] 2022-12-23 12:32
@ludgart please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:08
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:08 UTC
Labels: user vanished, awaiting testing
