### ISSUE TITLE
1.8 Knockback

### ISSUE THREAD

**Issue by Xd-pro** [kernitus/BukkitOldCombatMechanics#470] opened 2020-10-30 15:04 UTC
## Problem
I am not dealing the correct amount of sprint-hit (w/s tap) knockback and the vertical knockback is too low. In 1.8/1.7 The knockback deals lots of vertical and lots of horizontal if you are sprint-hitting or w/s tapping

## Proposed solution
Add some "modifiers to fix the 1.9+ knockback

**Comment by NOR7BE** [comment] 2020-11-17 18:05
Really useful suggestion.

**Comment by kernitus** [comment] 2020-11-24 10:45
Duplicate of #391

**Closed by kernitus** 2020-11-24 10:45 UTC
Labels: enhancement
