### ISSUE TITLE
Old armour durability can't eat gapples while damaged

### ISSUE THREAD

**Issue by Pulsih** [kernitus/BukkitOldCombatMechanics#586] opened 2022-01-13 13:30 UTC
## Information

* Server Version: 1.13.2

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/bbmhFRdN

* OldCombatMechanics config file: https://pastebin.com/wvaWr811

## Problem Description

If enabling the old-armor-durability feature, players can't eat gapples or stuff while being damaged, i think because the plugin update the player inventory while eating, and resetting the animation.

 
### To Reproduce
1. Just enable the old-armor-strenght feature and get hitted while eating

### Expected Behaviour
You should be able to eat gapples normally

### Actual Behaviour

You won't be able to eat gapples, and you will die ( My server is a FFACombo )

**Comment by kernitus** [comment] 2022-01-30 19:05
You mention both the old armour strength and old armour durability modules, which one is it that you think causes the issue?

**Comment by kernitus** [comment] 2022-04-23 18:34
Duplicate of #405

**Closed by kernitus** 2022-04-23 18:34 UTC
