### ISSUE TITLE
Error using the 1.17.1 Snapshot

### ISSUE THREAD

**Issue by CroaBeast** [kernitus/BukkitOldCombatMechanics#545] opened 2021-07-27 02:02 UTC
## Information

* Server Version: git-Purpur-1291 (MC: 1.17.1)

* OldCombatMechanics version: 1.10-SNAPSHOT (After trying the last snapshot on Jenkings, and can't work in 1.17.1, I try the lastest one in the issue #536 )

* Server Log File: https://paste.helpch.at/awepowevid.sql

* OldCombatMechanics config file: https://paste.helpch.at/rozenuzano.bash

## Problem Description

When hitting a mob with a Netherite Sword, a massive error spams in the console.

 
### To Reproduce
1. Have a server with git-Purpur-1291 (MC: 1.17.1) and Java 16
2. Install the version of #536 
3. Hit a mob with a netherite sword
4. Check the console to see the error.
5. Profit.

### Expected Behaviour
No error in the console.

### Actual Behaviour

Annoying errors in the console.

No more details needed.

**Comment by kernitus** [comment] 2021-07-27 15:03
Duplicate of #537

**Closed by kernitus** 2021-07-27 15:03 UTC
