### ISSUE TITLE
Customisable Mace attack damage

### ISSUE THREAD

**Issue by 2how** [kernitus/BukkitOldCombatMechanics#772] opened 2024-11-25 04:28 UTC
disable-attack-cooldown disables the cooldown for all items. The new items introduced in latest versions are designed to have a cooldown like the Maze, if the item does not have it, it becomes really overpowered.

Allow to toggle or disable the cooldown per item type, or have some sort of whitelist of items that will keep the cooldown.

**Comment by kernitus** [comment] 2024-12-02 19:41
I understand the sentiment, the problem is that the attack speed is a value in Minecraft that is set for the player, not on an individual item. This is how OCM operates and it would be difficult and performance intensive to do so on a per-item basis.

**Comment by 2how** [comment] 2024-12-02 20:52
I understand, I thought what OOC does is catch the item data sent to the player and replace the attack speed with the custom attack speed, with this approach you only need to filter the items with custom attack speed and apply the default value for the rest.

A way of balancing the Maze then might be removing the Attack modifier that the maze has based on player Y speed? So it keeps the special mechanics but it deals damage like a normal sword.

**Comment by kernitus** [comment] 2024-12-22 12:59
I think that's theoretically possible, we can allow setting the damage done by the weapon itself but we cannot change the attack speed on a per-item basis.

**Comment by kernitus** [comment] 2024-12-26 19:00
Duplicate of #757

**Closed by kernitus** 2024-12-26 19:00 UTC
Labels: enhancement
