### ISSUE TITLE
Players take no damage when pvping

### ISSUE THREAD

**Issue by zDragonS2** [kernitus/BukkitOldCombatMechanics#560] opened 2021-09-12 12:22 UTC
* Server Version: PAPER SPIGOT 1.12.2

* OldCombatMechanics version: 1.10.0

* OldCombatMechanics config file: https://pastebin.com/zMA6AdpQ

## Problem Description
At the time of pvp the players do not receive any type of damage. When I disable the "old-strength-armor" option, players die from 1/2 hits. I would like to make the pvp last longer but take damage

**Comment by kernitus** [comment] 2021-11-14 15:46
I'm gonna be needing an actual debug log with the damage being done and received on both sides to even have a clue what the problem might be. Please enable `debug` mode in the config.

**Comment by DotDebian** [comment] 2022-03-15 18:23
Hey @kernitus ,

I just had the same issue. I'm running 1.14.4 paperspigot with the latest plugin version, without anything else. Default config by the way.

I enabled debug:
`[19:17:54] [main/INFO]: [CHAT] <DqwnZ_> with modifier
[19:17:56] [main/INFO]: [CHAT] [Debug] Raw damage: 10.0
[19:17:56] [main/INFO]: [CHAT] [Debug] 0/9.0 last: 1.0
[19:17:56] [main/INFO]: [CHAT] [Debug] Mob: 0.0 Sharpness: 3.0
[19:17:56] [main/INFO]: [CHAT] [Debug] No ench damage: 7.0
[19:17:56] [main/INFO]: [CHAT] [Debug] Strength Modifier: 0.0
[19:17:56] [main/INFO]: [CHAT] [Debug] Weakness Modifier: 0.0
[19:17:56] [main/INFO]: [CHAT] [Debug] Base tool damage: 7.0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][ModuleOldToolDamage] Old DIAMOND_SWORD damage: 7.0 New tool damage: 8.0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][ModuleOldToolDamage] Old sharpness damage: 3.0 New: 6.25
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Base: 8.0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Weak: 0.0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Strength level: 0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Strength: 0.0
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Mob 0.0 Sharp: 6.25
[19:17:56] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] New Damage: 14.25
[19:17:59] [main/INFO]: [CHAT] <DqwnZ_> without modifier
[19:18:14] [main/INFO]: [CHAT] <Aizhyx> Je vois mais avec ton pl les logs spam xD
[19:18:32] [main/INFO]: [CHAT] [Debug] Raw damage: 10.0
[19:18:32] [main/INFO]: [CHAT] [Debug] 0/9.0 last: 1.0
[19:18:32] [main/INFO]: [CHAT] [Debug] Mob: 0.0 Sharpness: 3.0
[19:18:32] [main/INFO]: [CHAT] [Debug] No ench damage: 7.0
[19:18:32] [main/INFO]: [CHAT] [Debug] Strength Modifier: 0.0
[19:18:32] [main/INFO]: [CHAT] [Debug] Weakness Modifier: 0.0
[19:18:32] [main/INFO]: [CHAT] [Debug] Base tool damage: 7.0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][ModuleOldToolDamage] Old DIAMOND_SWORD damage: 7.0 New tool damage: 8.0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][ModuleOldToolDamage] Old sharpness damage: 3.0 New: 6.25
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Base: 8.0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Weak: 0.0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Strength level: 0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Strength: 0.0
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] Mob 0.0 Sharp: 6.25
[19:18:32] [main/INFO]: [CHAT] [DEBUG][EntityDamageByEntityListener] New Damage: 14.25
[19:18:37] [main/INFO]: [CHAT] <DqwnZ_> oui jsais
`

With or without the old-strength-armor, same debug. But without, we die of 13 hits, with the module enabled we don't lose any hearth.

We're both on a diamond suit, Protection IV, Unbreaking III, with diamond swords Sharpness V, Unbreak. III, Fire Aspect II.

**Comment by DotDebian** [comment] 2022-03-15 19:33
Update: logs were from the attacker's PoV. From the attacked player, we get this:
![image](https://user-images.githubusercontent.com/20359522/158457108-43cdb73f-d375-48eb-9eb8-2d4cc8dbda79.png)

**Comment by kernitus** [comment] 2022-12-23 12:32
@DotDebian @zDragonS2 please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:08
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:08 UTC
Labels: user vanished, awaiting testing
