### ISSUE TITLE
Custom damage attributes on items are disregarded

### ISSUE THREAD

**Issue by AstralForce** [kernitus/BukkitOldCombatMechanics#320] opened 2019-07-14 22:18 UTC
- Server version :  1.13.2
- OldCombatMechanics version : 1.7.3
- Server log file : https://pastebin.com/NnFcEWNk
- OldCombatMechanics config file : https://pastebin.com/BSxBALDc

## Problem Description
> Hi, I use OldCombatMechanics and a plugin known as MMOItems on my server. MMOItems allows for me to make special items that do configurable amounts of damage (as well as various abilities and things). However, with OldCombatMechanics installed, the damage for MMOItems doesn't work. Despite me setting the attack damage of a custom item to 100 damage, it will do the standard damage of that item. This only happens when OldCombatMechanics is installed.

**Comment by gvlfm78** [comment] 2019-07-15 09:35
Is MMOItems the premium resource on Spigot? I can't really check its code to see where the conflict would be if that's the case

**Comment by Indyuce** [comment] 2019-07-17 12:34
Hey there, I'm the author of MMOItems. I've just added you to the buyers list so you should be able to download the resource and check its code. If you have any question about how MI handles damage, hop on my Discord. Anyways I might have an idea what the issue is.

**Comment by gvlfm78** [comment] 2019-07-22 12:09
We are looking into this issue and it seems we have to take into account attributes when a damage event occurs.

**Comment by AstralForce** [comment] 2019-07-31 00:19
Any progress? Not to seem pushy, I just want to plan if I will be able to start using OCM again... I have a temporary replacement thats kinda janky in right now... lmao

**Comment by Rayzr522** [comment] 2020-06-26 19:52
@kernitus correct me if I'm wrong, but we just need to add this as yet one more thing taken into account in [OCMEntityDamageByEntityEvent.java](https://github.com/kernitus/BukkitOldCombatMechanics/blob/master/src/main/java/kernitus/plugin/OldCombatMechanics/utilities/damage/OCMEntityDamageByEntityEvent.java), right? we already account for crits, potion effects, etc. just need to add attributes as something we check for, right?

**Comment by kernitus** [comment] 2020-06-26 20:02
@Rayzr522 I believe it would also have to be calculated correctly before any modification is applied, and then re-added after OCM has done its thing.

**Comment by kernitus** [comment] 2021-06-09 21:11
Fixed with b177662

**Closed by kernitus** 2021-06-09 21:11 UTC
Labels: bug, help wanted, incompatibility
