### ISSUE TITLE
Old Armour Strength netherite damage too small

### ISSUE THREAD

**Issue by xFreakss** [kernitus/BukkitOldCombatMechanics#603] opened 2022-03-29 14:43 UTC
## Information

* Server Version: Purpur 1.18.2 - 1599

* OldCombatMechanics version: b#86

* Server Log File: https://pastebin.com/EpZEipb0

* OldCombatMechanics config file: https://pastebin.com/0TFLzdku

## Problem Description

1_ Anything wearing a full netherite set is literally invincible if old-armour-strength is enable
2_ There are some mobs (i found a slime) hitting players 10 times in a second, bit more or bit less.
 
### To Reproduce
1. enchant a full netherite set and go pvp
2. let a slime hit ya

### Expected Behaviour
1. not being invincible
2. not being hit more than 1 time per hit
### Actual Behaviour

1. being invincible
2. being hit 102391204981 times/sec by a monster

**Comment by kernitus** [comment] 2022-12-23 12:30
@xFreakss please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:06
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:06 UTC
Labels: bug, user vanished, awaiting testing
