### ISSUE TITLE
Rabbit's foot not consumed and brewing fails

### ISSUE THREAD

**Issue by cobrex1** [kernitus/BukkitOldCombatMechanics#574] opened 2021-11-20 19:26 UTC
1.17.1 paper release 386 

OldCombatMechanics 1.10.0 tested with dev versions 79, 85 and 86

There are no errors on console.

Use any of these and place a brewing stand and brew either with water or awkward potion, the rabbit foot is not consumed. Disable the plugin and the brewing consumes the rabbit foot as expected and the potion is brewed.

**Comment by kernitus** [comment] 2021-12-21 11:21
Does disabling the brewing module in the config also make it work again?

**Comment by cobrex1** [comment] 2021-12-22 06:52
Thank you - I had not tried that. Yes disabled that option and the rabbit foot is now consumed.

**Comment by cobrex1** [comment] 2021-12-26 07:59
Also, are you aware of any issues linking McMMO bleed (serrated edge) and OldCombat? When a player uses serrated edge the bleed effect is significantly exaggerated and wonder if the two don't play nice together.
Thanks

**Comment by kernitus** [comment] 2022-04-24 16:09
Duplicate of #571

**Closed by kernitus** 2022-04-24 16:09 UTC
