### ISSUE TITLE
Players getting kicked upon changing their world with various config settings

### ISSUE THREAD

**Issue by Aevox01** [kernitus/BukkitOldCombatMechanics#424] opened 2020-07-15 19:20 UTC
## Information

* Server Version: 1.15.2-R0.1-SNAPSHOT

* OldCombatMechanics version: 1.8.1

* Server Log File: Console doesn't say anything at all.

* OldCombatMechanics config file: https://pastebin.com/ay6Js3vS

## Problem Description

This bug does not occur if I use the standard config (means without changing the generated one at all). Once I use an edited config and a player changes the world everyone gets disconnected (sometimes it gives a remotehost error, sometimes just some customized network error that says that the server went down while it didnt).

 
### To Reproduce
1. Put the config that's shown in the pastebin link
2. Change worlds (A simple usage of multiverse is enough for that)
3. Get kicked

### Expected Behaviour
Well, I don't expect it to kick players. I just expect it to work as intended aka to not kick anyone.

### Actual Behaviour

As stated above, multiple times, it kicks the whole server while the server itself doesn't crash or something (You can simply rejoin after you got kicked)

**Comment by Rayzr522** [comment] 2020-07-16 16:59
looks to be a potential duplicate of #403 and the way that scoreboards are handled -- can you try disabling `disable-player-collisions` and see if the problem goes away? @Aevox01 

also even if there don't seem to be any OCM-related errors on console, console logs often have tidbits of information that are more useful than you might expect. a console log could be quite helpful

**Comment by Aevox01** [comment] 2020-07-18 16:27
It's pretty much what you described. I changed the config in the way that is needed for us and put `disable-player-collisions` on `false`. The bug no longer occurs now. Yet I would like to put this on true so a bug fix would still be appreciated. Is the console log still needed?

**Comment by Rayzr522** [comment] 2020-07-19 04:02
good to know, hmmm. yes we need a console log please

**Comment by I-Al-Istannen** [comment] 2020-07-19 09:25
I second that. I just tried your steps:
[Imgur video](https://i.imgur.com/o4PwmTW.mp4)

Do you have any plugins creating or meddling with scoreboards?

**Comment by kernitus** [comment] 2020-10-03 15:12
@Aevox01 could you please try [this test version](https://ci.rayzr.dev/job/OldCombatMechanics/46/) with the new patch? We think it might fix the issue.

**Closed** 2020-11-24 13:58 UTC
Labels: awaiting testing, user vanished
