### ISSUE TITLE
1.18 Collisions reflection error

### ISSUE THREAD

**Issue by GAMERFORCE99** [kernitus/BukkitOldCombatMechanics#601] opened 2022-03-14 14:54 UTC
idk whats wrong with this error or how to fix this

```
[14:53:23 WARN]: [OldCombatMechanics] Error reloading module 'Disable Player Collisions'
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "method" is null
at kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.invokeMethod(Reflector.java:101) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$ScoreboardTeamWither.build(V17TeamPacket.java:198) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.lambda$setCollisionRule$4(V17TeamPacket.java:127) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.reflection.Reflector.getUnchecked(Reflector.java:220) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.setCollisionRule(V17TeamPacket.java:112) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket$PacketAccess.createTeamPacket(V17TeamPacket.java:150) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.V17TeamPacket.create(V17TeamPacket.java:51) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.packet.team.TeamPacket.create(TeamPacket.java:55) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.teams.TeamUtils.craftTeamCreatePacket(TeamUtils.java:37) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.createAndSendNewTeam(ModulePlayerCollisions.java:104) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.createOrUpdateTeam(ModulePlayerCollisions.java:91) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.module.ModulePlayerCollisions.reload(ModulePlayerCollisions.java:115) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.utilities.Config.lambda$reload$0(Config.java:81) ~[OldCombatMechanics.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at kernitus.plugin.OldCombatMechanics.utilities.Config.reload(Config.java:79) ~[OldCombatMechanics.jar:?]
at kernitus.plugin.OldCombatMechanics.OCMCommandHandler.onCommand(OCMCommandHandler.java:60) ~[OldCombatMechanics.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1371) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277) ~[paper-1.18.1.jar:git-Paper-216]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nivcoo** [comment] 2022-03-15 17:19
I've same issue with blank config in 1.18.2

**Comment by kernitus** [comment] 2022-03-17 20:27
@I-Al-Istannen did the packet interface change again or is this unrelated?

**Comment by kernitus** [comment] 2022-03-17 20:29
Duplicate of #591

**Closed by kernitus** 2022-03-17 20:29 UTC
