### ISSUE TITLE
Cant eat gapples in row.

### ISSUE THREAD

**Issue by razor257** [kernitus/BukkitOldCombatMechanics#597] opened 2022-03-10 12:53 UTC
## Information

* Server Version: 1.16.5 and 1.15.2

* OldCombatMechanics version: 1.10.0

* Server Log File: https://pastebin.com/BLJuErMA 

## Problem Description

You can't eat gapples in row which isn't default vanilla setting it's dangerous for players in combat as they could get killed when they should be able to eat and stay alive.

https://youtu.be/JbjGXrFLHWk

### To Reproduce
1. Setup your config like this :
```
old-golden-apples:
  enabled: true
  old-potion-effects: true
```
2. Try to eat gapples while holding and not letting go of the mouse button. You can start to jump but can also stand still.
3. Side note - the `no-conflict-mode: false/true` in this module doesn't change anything.

### Expected Behaviour
Can eat gapples in row.

### Actual Behaviour
Cant eat gapples in row.

**Comment by kernitus** [comment] 2022-04-23 18:05
Is this the same issue as #586 ?

**Comment by kernitus** [comment] 2022-04-23 18:34
Duplicate of #405

**Closed by kernitus** 2022-04-23 18:34 UTC
