### ISSUE TITLE
Console Error and Plugin disable

### ISSUE THREAD

**Issue by SaveStandard** [kernitus/BukkitOldCombatMechanics#436] opened 2020-07-30 15:15 UTC
Server Version: 1.14.4

OldCombatMechanics version: Jenkins dev #40

Server Log File: https://pastebin.com/prT6cjX1

OldCombatMechanics config file: https://pastebin.com/DbVfXJr1

**Comment by Rayzr522** [comment] 2020-08-07 06:31
duplicate of #437, see [this comment](https://github.com/kernitus/BukkitOldCombatMechanics/issues/437#issuecomment-669449688) for a dev build that should fix the error

**Closed by Rayzr522** 2020-08-07 06:31 UTC
