### ISSUE TITLE
Unbreaking not working with elytras

### ISSUE THREAD

**Issue by Looowi** [kernitus/BukkitOldCombatMechanics#413] opened 2020-06-28 14:53 UTC
## Information

* Server Version: Paper 1.15.2 (build 205)

* OldCombatMechanics version: 1.8.0

* Server Log File: 

* OldCombatMechanics config file: 

## Problem Description

When using the old durability, the unbreaking enchantment dos nothing on elytras. 

 
### To Reproduce
1. Fly with elytra for few seconds
2. Check durability
3. Fly the same way with elytras having unbreaking 3
4. Check durability (they will be the same)

### Expected Behaviour
Elytras with unbreaking 3 should be able to fly a longer time.

### Actual Behaviour

They dont.

**Comment by kernitus** [comment] 2020-06-29 11:04
Can you please check if this issue is present on the [dev builds](https://ci.rayzr.dev/job/OldCombatMechanics/)? This may be related to issue #390.

**Comment by kernitus** [comment] 2020-06-29 11:05
Duplicate of #390

**Closed by kernitus** 2020-06-29 11:05 UTC
Labels: duplicate
