### ISSUE TITLE
Error when placing a block on 1.12.2 server

### ISSUE THREAD

**Issue by pabloalba16** [kernitus/BukkitOldCombatMechanics#726] opened 2024-04-03 12:30 UTC
## Information

* Server Version: Reaper 1.12.2 (Paper fork)

* OldCombatMechanics version: tried with 2.0.1 and latest dev on: https://ci.rayzr.dev/job/OldCombatMechanics/217/

* Server Log File: 
<details><summary>Server Log</summary>
  
``` console
https://pastebin.com/Ev1N91nk
```
</details>

* OldCombatMechanics config file: default one, nothing modified
<details><summary>config.yml</summary>
  
``` yaml

```
</details>

### To Reproduce
 
1. Make a 1.12.2 server
2. place a block
3. lookk at the console for the error

### Expected Behaviour

No errors to show
### Actual Behaviour

Everytime you place a block you get that error

**Comment by kernitus** [comment] 2024-04-03 18:16
Duplicate of #719

**Closed by kernitus** 2024-04-03 18:16 UTC
Labels: investigate
