### ISSUE TITLE
Blocking closer to 1.8

### ISSUE THREAD

**Issue by YOMA8338** [kernitus/BukkitOldCombatMechanics#776] opened 2024-12-24 07:50 UTC
I think it would be better in 1.21.4 if you used the component [consumable={animation:block,consume_seconds:2099999999}] on the sword to make the sword block closer to 1.8.
You can do this in 1.21.3, but it will not display correctly in 1st person view in 1.21.3...
I think it would be nice to use the ViaAPI to show only players with 1.21.4 or higher with sword blocks like in 1.8, even in 1.21.3 or earlier versions. (I don't know if this can be done or not).
Also, please add the ability to set the shield guard delay to 0, because if you hit the right click repeatedly, the shield damage reduction on the sword block will not work.

## Problem
SwordBlocking is using a shield.(In 1.21.4)
Attacks while SwordBlocking do not reduce damage.

## Proposed solution
In 1.21.4, add a component [consumable={animation:block,consume_seconds:2099999999}] to the sword to allow sword blocking like in 1.8.
Add a function to eliminate the delay when guarding with a shield.

**Comment by kernitus** [comment] 2024-12-24 12:43
Duplicate of #769

**Closed by kernitus** 2024-12-24 12:43 UTC
Labels: enhancement
