### ISSUE TITLE
Gaps on attack bug

### ISSUE THREAD

**Issue by sjander12** [kernitus/BukkitOldCombatMechanics#530] opened 2021-06-07 18:02 UTC
## Information

* Server Version: 1.16.5 but the bug is in 1.12

1.9.0

* OldCombatMechanics version: 1.9.0

* Server Log File: none

* OldCombatMechanics config file: 
https://pastebin.com/yvfgFnMG
## Problem Description

When you get hit you sometimes cant eat your gapple

 
### To Reproduce
https://youtu.be/TyHV0IeIgag

### Expected Behaviour
want it to eat the gapple when your getting hitted

**Comment by sjander12** [comment] 2021-06-08 11:15
btw this only happens when i have old-armour-durability:true
When i set it on false its fine

**Comment by kernitus** [comment] 2021-06-08 23:38
Thank you for this video, it makes it clearer what is going wrong. However, I think this is a duplicate of #405 so we should keep discussion over there.

**Closed by kernitus** 2021-06-08 23:38 UTC
