### ISSUE TITLE
Shield Damage Reduction not working as intended

### ISSUE THREAD

**Issue by SalomonPicos** [kernitus/BukkitOldCombatMechanics#627] opened 2022-10-12 15:37 UTC
## Information

* Server Version: 1.19.2 git-Paper-189

* OldCombatMechanics version: 1.11.0

* Server Log File: https://mclo.gs/6f06v8C

* OldCombatMechanics config file: https://hastebin.com/janegeluze.yaml

* Debug output when being hitted (crit) while using shield: https://imgur.com/dMFNgO5

## Problem Description
When i get hit without using shield i receive 0 damage (with the armor set i have) while when i use the shield i receive 2 hearts of damage

1. Using shield
2. Get hit by a player

### Expected Behaviour
I should receive less damage while using shield i suppose

### Actual Behaviour
I receive more damage while using shield then when i'm not using it

**Comment by kernitus** [comment] 2022-12-04 15:17
I will look into this together with the rest of the damage rework.

**Comment by kernitus** [comment] 2022-12-23 12:29
Hello @SalomonPicos please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:05
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:05 UTC
Labels: user vanished, awaiting testing
