### ISSUE TITLE
Old-Tool-Damage & Disable-Player-Crits

### ISSUE THREAD

**Issue by G4stavoM1ster** [kernitus/BukkitOldCombatMechanics#502] opened 2021-03-09 01:39 UTC
**« Information: »**

• Server Version: 1.16.5

• OldCombatMechanics version: 1.9.0

**« Problem description: »**

• The old-tool-damage system does not respect the disable-player-crits option enabled in paper.yml

**« Steps to reproduce the behavior: »**

1. Enable old-tool-damage in config.yml
2. Enable disable-player-crits in paper.yml
3. Try to make a critical damage in a mob or something.

**« Expected behaviour: »**

• Critical damage cannot be done with the config option enabled in paper.yml

**« Actual behaviour »**

• The player still manages to deal critical damage even with the config option enabled in paper.yml

**Comment by kernitus** [comment] 2021-03-24 19:04
Duplicate of #410

**Closed by kernitus** 2021-03-24 19:04 UTC
