### ISSUE TITLE
Various issues with shield blocking and offhand

### ISSUE THREAD

**Issue by itsmeow** [kernitus/BukkitOldCombatMechanics#383] opened 2020-05-04 21:01 UTC
## Information
* Server Version: Paper-227 1.15.2
* OldCombatMechanics version: 1.7.4
* OldCombatMechanics config file: https://pastebin.com/b9pcF2Pw

## Problem Description
1. Using shield blocking and disconnecting while doing it causes the shield to remain in inventory
2. Because of the above, if you disconnect while blocking and something is in your offhand, you lose it forever
3. If the offhand shield breaks (try an OP power bow), it becomes very buggy and doesn't return until the server restarts

### To Reproduce
1. Get kicked or disconnected while blocking (with something in offhand or without)
2. See Error

1. Use Power 32000 bow on someone blocking with shield
2. Shield breaks
3. Person's shield no longer functions and randomly sputters in and out

### Expected Behaviour
Disconnection should cause the shield to be removed and replaced with the original item
Shields should either not break even with powerful means or properly return when broke

### Actual Behaviour
Item is replaced when disconnected
Shield randomly appears and disappears rapidly after being broken until server is restarted

**Comment by kernitus** [comment] 2020-05-18 12:51
@itsmeow I am unable to reproduce either of these issues, at least in the [latest dev builds](https://ci.rayzr.dev/job/OldCombatMechanics/). They may have been fixed along the way, can you please check with a newer version?

**Comment by Rayzr522** [comment] 2020-06-26 19:54
User vanished, closing pending further response from @itsmeow

**Closed by Rayzr522** 2020-06-26 19:54 UTC
Labels: bug, not enough info, user vanished
