### ISSUE TITLE
Crazy unarmed damage

### ISSUE THREAD

**Issue by klaidosHka** [kernitus/BukkitOldCombatMechanics#611] opened 2022-05-31 17:44 UTC
Hello 👋
Because no one opened a ticket here regarding the newest version (or at least I can't see), I'm opening it...

`The problem is that the unarmed attacks are totally ignoring armors, it's like people are shredding others with bare hands.`

Not sure if this happens when something is being kept in the hand (sword/tool/w.e), but for sure it happens, when you are holding nothing. Just spam a bit and P6 full-netherite person will be dead in around 3 seconds. From bare hands.

Quite some people mentioned it in spigot reviews section, atm.

**Comment by klaidosHka** [comment] 2022-06-02 16:17
old-potion-effects.strength.addend, disable it (enabled by default), fucks everything up. Great defaults. 😀

**Comment by kernitus** [comment] 2022-06-13 22:38
Thank you for opening a ticket, the spigot reviews are not the place for issue reporting.
Could you clarify more what you're saying? What happens _with_ armour and _without_ armour?
Does disabling the `old-potion-effects` module make a difference?
Most importantly, what damage do you expect in those situations, and what do you get instead?

**Comment by klaidosHka** [comment] 2022-06-14 07:18
> Thank you for opening a ticket, the spigot reviews are not the place for issue reporting. Could you clarify more what you're saying? What happens _with_ armour and _without_ armour? Does disabling the `old-potion-effects` module make a difference? Most importantly, what damage do you expect in those situations, and what do you get instead?

This happens:
(Lets say we have Player A and Player B (further - A, B))

A is fully armored, netherite materials, Prot4-10, whatever. B is unarmed, has nothing on himself, only Strength 2 effect. B hits A a few times with a speed of 8-10 clicks per second, A dies instantly, in less than 1.5 seconds. Why? B, for some reason, deals ridiculous damage with its second/third hit, while he should deal around 1-3 damage, not 15+.

Whether *old-potion-effects* disabling would fix everything, I am not sure, will try out and edit the message. But! Disabling this path: `old-potion-effects.strength.addend` fixes the ridiculous damage against armored people, but not against armorless people. **Unarmed A player** vs **Unarmed B player with Strength 2 effect** would lead to B player winning instantly anyways, but not if A player would have any armor (didn't test if **'ANY ARMOR'** for real, just the ones with enchants)

**Comment by kernitus** [comment] 2022-07-02 12:37
Alright thanks for the extra info, I will have to perform some tests on this to suss out where the issue actually lies. Also, all `addend` does is turn the strength modifier into +x instead of *x, because this was changed with 1.9.

**Comment by kernitus** [comment] 2022-12-23 12:30
@klaidosHka please try the [new test builds](https://ci.rayzr.dev/job/OldCombatMechanics/), where I have rewritten most of the calculations that deal with damage.

**Comment by kernitus** [comment] 2023-02-01 13:06
Closing due to rewrite of all damage calculation code. Please open a new issue with debug logs from the latest version if you think the issue is still present.

**Closed by kernitus** 2023-02-01 13:06 UTC
Labels: bug, user vanished, awaiting testing
