### ISSUE TITLE
Disable Player Collisions does not work

### ISSUE THREAD

**Issue by LeehamElectronics** [kernitus/BukkitOldCombatMechanics#414] opened 2020-06-30 01:41 UTC
Hi, I am using Old Combat Mechanics 1.8.0 and PaperMC #374 1.15.2
At first players were getting kicked from the game when using the following config:

  comment.... This is to disable player collisions
  comment... This is now compatible with scoreboard and tablist-editing plugins
  enabled: true
  worlds: []

and I verified that it was OCM causing the issue by removing that plugin and testing. Now that issue somehow stopped occurring, however I can not disable player collisions, I have tried setting the OCM config to true to no avail, and I also disabled Paper's option for player collisions: 
enable-player-collisions: false
Is there any other way to disable player collisions?
Thanks

EDIT: players still get kicked from the game with a score board error when the “disable player collisions” is set to true in the OCM config, is there a fix for this? I believe other people are having this issue too, and while ur at it, how can we disable player collisions cause it’s not working.
Thanks

**Comment by kernitus** [comment] 2020-07-01 10:18
Duplicate of #403

**Closed by kernitus** 2020-07-01 10:18 UTC
Labels: duplicate
