### ISSUE TITLE
Damage speed issue on 1.17.1

### ISSUE THREAD

**Issue by ElFlyGod** [kernitus/BukkitOldCombatMechanics#558] opened 2021-08-23 17:18 UTC
* Server Version:  1.17.1
* OldCombatMechanics version: 1.10.0
* OldCombatMechanics config file:  https://paste.helpch.at/kinaciboco.bash

## Problem Description
Hits are registering super fast if you click fast, compared to a vanilla fast attack speed sword, ocm version is extremely fast,

Below are gifs showcasing how it should be vs how it is on oldcombatmechanics
This behavior also applies to mobs not just players.

1. Spawn a vanilla wood sword with fast attack speed /give ElFly wooden_sword{AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:500,Name:"generic.attack_speed",UUID:[I;-121723,22324,20043,-44648]},{AttributeName:"generic.attack_damage",Amount:4,Name:"generic.attack_damage",UUID:[I;-121723,22424,20043,-44848]}]} 1

2. Compare speed with ocm enabled, using a regular sword
3. Unload ocm, try with command spawned sword, will notice that the spawned one is doing the proper speed while OCM previously was much faster

### Expected Behaviour
Not sure what to call it but you should be able to attack much slower
This is how it should look: https://i.gyazo.com/050fe2625647a4242cb3f33aef45ccb2.mp4

### Actual Behaviour
Clicking fast makes health go down A LOT faster.
This is how it looks now (super fast): https://i.gyazo.com/fff837925d137f8b2f5b13d50cba035b.mp4

**Comment by kernitus** [comment] 2021-08-29 12:06
I believe this is a duplicate of #554

**Closed by kernitus** 2021-08-29 12:06 UTC
