### ISSUE TITLE
HELP How can i disable critical damage

### ISSUE THREAD

**Issue by Xxyuri2005xX** [kernitus/BukkitOldCombatMechanics#518] opened 2021-05-12 12:35 UTC
Hello OCM Team,
how can idisable the critical sword attack on OCM plugin on Paper 1.12.2? (i am using viabackwards to allow 1.8)

**Comment by refractored** [comment] 2021-05-16 03:25
iirc you can disable it in paper.yml

**Comment by Xxyuri2005xX** [comment] 2021-05-16 14:42
where i can disable them? can you give me the right name of what i need to change?

**Comment by kernitus** [comment] 2021-06-02 13:25
Duplicate of #410

**Closed by kernitus** 2021-06-02 13:25 UTC
