### ISSUE TITLE
Make toggle messages configurable

### ISSUE THREAD

**Issue by nikitushu2** [kernitus/BukkitOldCombatMechanics#521] opened 2021-05-16 07:23 UTC
When I toggle between 1.9 and 1.8 pvp modes, the message `[OCM] Attack cooldown enabled/disabled appears`. How to change this message?

**Comment by kernitus** [comment] 2021-06-02 13:17
This is not currently configurable, but can be made so.

**Comment by kernitus** [comment] 2021-06-02 13:20
Duplicate of #493

**Closed by kernitus** 2021-06-02 13:20 UTC
Labels: enhancement
