### ISSUE TITLE
Please... Fix the double hit glitch on crit (Gamebreaking PvP Bug)

### ISSUE THREAD

**Issue by Denelix** [kernitus/BukkitOldCombatMechanics#443] opened 2020-08-03 20:18 UTC
## Information
* Server Version: BUKKIT 1.16.1 and alot of other servers

* OldCombatMechanics version: 1.8.1 but has been happening in older versions too

* Server Log File: 
(: 
* OldCombatMechanics config file: 
Even with the config all on true or false this still occurs. config does not matter

## Problem Description
This plugin is great and all but there is literally one problem in the whole. because of this glitch, I have lost scholarships and have had to get in contact with every server owner I like to PVP on to switch their old PVP plugin. I have videos of this happening on a few other servers begging to switch to back to the roots only because of this bug. I would use this plugin on my own server always... but this bug is so game breaking to where I just can't.

### To Reproduce
I used skript [https://pastebin.com/0mMpADLc] to show how many times i have hit a player in a second but the hit delay in minecraft is 10 ticks and criting someone increases this to 4 hits for some reason.

1. Go to any "hittable" entity then jump and swing at the enemy
2. you will see it looks like you hit the enemy 2 times but really they were hit twice in 1 tick 
### Expected Behaviour
hitting them 2 times a second like vanilla Minecraft
### Actual Behaviour
hit someone 4 times in 1 second for some reason.

https://youtu.be/_liXEOcC4bQ Double hit instantly (Esports footage watch in .25 speed to see hearts go down twice instnatly)
https://youtu.be/5ViZO7ZLuLs Double hit instantly (Esports footage watch in .25 speed to see hearts go down twice instnatly)
https://youtu.be/1HDR1danKX0 Slowed down footage of multiple hits in one only from crit causes
https://youtu.be/pb9-iITDMPk me using the skript to show this happening.
Kind of rushed this bug report I have to do something but I'm sure you can understand what is going on here. Sorry if it's messy thank you for reading.

**Comment by Rayzr522** [comment] 2020-08-07 06:08
first off, i want to say thank you for putting this much effort into reporting a bug. it's more than can be said for most people, and it is immensely appreciated.

however, before you go around telling servers to stop using OCM, please do a little more investigation. I can achieve up to 4 hits per 1 second without crits, without having OCM installed, tested from 1.14-1.16 (I presume I could keep going back to 1.9 and find the same results, but don't have the time to do so -- the exact version this behavior became present is irrelevant tho). this is not a bug in OCM, simply the way that hit detection works in 1.9+ now.

for reference, I tested this with:
- Tuinity 1.16.1
- Spigot 1.16.1
- Spigot 1.15.2
- Spigot 1.14.4

with nothing but [HitCounter](https://github.com/Rayzr522/HitCounter) as well as ViaVersion for the older versions so that I did not have to install client versions that I will never use again.

i'd love to see some documentation somewhere that this was actually a 1.9+ combat change, but I don't say that because I doubt it was, rather because it would make this easier to fix with a module. alas, we will likely have to do our own investigation to figure out how to fix hit detection.

i don't think this is the first time similar "bugs" have been reported or this feature has been requested, but fixing this will require a whole new module to be built. without the information readily available on how the hit detection used to work vs how it works now, this is not a trivial process, and requires lots of digging to find concrete numbers before we could even start.

@Denelix if you happen to have any resources on the topic of how hit detection worked (from an actual technical perspective) in 1.8 vs 1.9+, i'd greatly appreciate that you share them. in the meantime, please do not tell anyone else that this is a bug in OCM, as it is no less present without OCM than it is with it. it's simply a change in behavior, and OCM is still quite effective in changing most combat mechanics. obviously we don't have support for fixing everything, but we are getting there, so in the meantime, OCM is still providing a drastic improvement over plain 1.9 combat.

I'm closing this as a duplicate of #19, but I will link back to this issue there, as this provides significantly more information about the changes than at least anything we had before.

**Closed by Rayzr522** 2020-08-07 06:08 UTC
Labels: investigate
