### ISSUE TITLE
Tool damage not working with QuantumRPG

### ISSUE THREAD

**Issue by ElytraPvP** [kernitus/BukkitOldCombatMechanics#347] opened 2019-09-16 15:01 UTC
- Server version:  1.14.4 paper
- OldCombatMechanics version:  1.7.4
- Server log file: Nothing special here no errors
- OldCombatMechanics config file: 

> Tool damage does not work properly on axes for me
![image](https://user-images.githubusercontent.com/53577866/64968953-ee888b80-d89a-11e9-9409-fb908d0a55f5.png)
Most axes do 9 damage no matter what i set it to. However if i set it to something more than 9 it will work 
[configexample.yml.txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/3616846/configexample.yml.txt)

**Comment by kernitus** [comment] 2019-09-17 10:55
If you enabled `debug` mode in the config.yml, what are the reported damage values when using axes?

**Comment by ElytraPvP** [comment] 2019-09-17 10:57
I have a plug-in that logs the damage and I can see that it is 9 I know
it’s 9 I’ve done tests with mobs on it as well

**Comment by kernitus** [comment] 2019-09-17 10:58
I will need to see the OCM debug output.

**Comment by ElytraPvP** [comment] 2019-09-17 10:59
Alright I will do so when I’m home in 5 hours :)

**Comment by ElytraPvP** [comment] 2019-09-17 17:29
![image](https://user-images.githubusercontent.com/53577866/65064748-f6b6f880-d978-11e9-80a7-b405dc108d09.png)
 this does 9 damage

**Comment by ElytraPvP** [comment] 2019-09-18 14:41
buuuump

**Comment by ElytraPvP** [comment] 2019-09-19 16:29
i really  need this fixed soon

**Comment by Rayzr522** [comment] 2019-09-19 23:39
@ElytraPvP sorry for the late reply. What other plugins do you have?

**Comment by Rayzr522** [comment] 2019-09-19 23:41
Actually, seeing the output from [EventChecker](https://github.com/RayzrDev/EventChecker) would help.

Just install it and do `/listeners org.bukkit.event.entity.EntityDamageByEntityEvent`.

**Comment by ElytraPvP** [comment] 2019-09-20 02:31
[19:29:12 ERROR]: Ambiguous plugin name `OldCombatMechanics' for files `plugins\OldCombatMechanics.jar' and `plugins\OldCombatMechanics - 1.7.4.jar' in `plugins' odd that i just got this error first time when oppening the server but i havent done anything haha

**Comment by Rayzr522** [comment] 2019-09-20 02:33
That means you have two OldCombatMechanics JARs in your server folder. Delete both and re-download the latest dev build from [the Jenkins build server](https://ci.rayzr.dev/job/OldCombatMechanics).

**Comment by ElytraPvP** [comment] 2019-09-20 02:37
ive eddited the jar slightly

**Comment by ElytraPvP** [comment] 2019-09-20 02:37
Ive made it so the shield pops up on your screen when you right click with an axe and with a sword dont know if that would effect damage on axe though

**Comment by ElytraPvP** [comment] 2019-09-20 02:38
I used 1.7.5

**Comment by Rayzr522** [comment] 2019-09-20 02:39
Feel free to keep a copy of the JAR you modified but for further testing we are going to need you to use a stock JAR. Otherwise we have no way to confirm it isn't an issue with a change you made or an issue with a bug that was patched after the version you modified.

**Comment by ElytraPvP** [comment] 2019-09-20 02:42
Alright Also i got this when typing the command
![image](https://user-images.githubusercontent.com/53577866/65295216-9b436100-db58-11e9-8276-75d3c58c9dca.png)

**Comment by Rayzr522** [comment] 2019-09-20 02:44
Don't worry about the tab completion error, that should be fine. You can even just copy and paste the full command in if you want. Does actually running the command show you results?

**Comment by ElytraPvP** [comment] 2019-09-20 02:48
![image](https://user-images.githubusercontent.com/53577866/65295505-7996a980-db59-11e9-8c78-dfad81e8b7a8.png)
with the new jar it still does 9 dmg

**Comment by Rayzr522** [comment] 2019-09-20 02:49
Can you not even run the command? That looks like just an error with tab completion (which is odd but still), it should not affect the actual running of the command.

**Comment by ElytraPvP** [comment] 2019-09-20 02:51
Yes it said at the bottom i issued the command and there is no errors after that

**Comment by ElytraPvP** [comment] 2019-09-20 02:51
What should I do next

**Comment by Rayzr522** [comment] 2019-09-20 02:52
I need to see the output from the command... at the very least, it should list OldCombatMechanics' listener for the event.

**Comment by ElytraPvP** [comment] 2019-09-20 03:05
![image](https://user-images.githubusercontent.com/53577866/65296303-e90d9880-db5b-11e9-8458-59992e4420ac.png)
the second line is the output there is  no console output

**Comment by ElytraPvP** [comment] 2019-09-20 03:06
console has been empty since

**Comment by ElytraPvP** [comment] 2019-09-20 03:06
![image](https://user-images.githubusercontent.com/53577866/65296338-093d5780-db5c-11e9-95aa-28396fe79a02.png)
 these are the plugins atm

**Comment by kernitus** [comment] 2019-09-20 07:38
How do you even know it's doing 9 damage? OCM's debug output showed it as doing 7

**Comment by ElytraPvP** [comment] 2019-09-20 07:40
Because I have a plug-in quantum RPG that says how much damage I do it
says 9 as a hologram when u hit something and if I set it to 12 damage or
more it will show that number but under 9 on axes it doesn’t work but it
works fine on swords

**Comment by Rayzr522** [comment] 2019-09-20 11:12
Not sure what's going on with EventChecker... maybe it's not compatible with 1.14.4.

But my guess is that quantum RPG is checking damage *before* OCM modifies it. You should actually test it with something else, such as a scoreboard objective that shows player health below the player name, and then see how much it decreases when you hit a player.

**Comment by ElytraPvP** [comment] 2019-09-21 04:30
I know its 9 damage i tested it with mobs either way quantumrpg shows damage if i increase the axe damage to like 20 it will say 20 its just when its under, very strange

**Comment by I-Al-Istannen** [comment] 2019-09-21 09:03
If you can make a minimum verifiable/working example (i.e. the minimal amount of plugins needed to reproduce this) I will have a look.

To do this, please try it out with *just OCM and QuantomRPG* and see if it stays at 9. If that works, I would add half of the other plugins, see if it is broken and then bisect it like that.

**Comment by ElytraPvP** [comment] 2019-09-21 10:41
Ill give it a go in a bit thank you

**Comment by ElytraPvP** [comment] 2019-09-22 07:00
Just tested it with essentials, ocm and quantumrpg and it still does 9 damage and the debugg text is indentical what should i try next

**Comment by I-Al-Istannen** [comment] 2019-09-22 15:06
I just noticed quantum RPG is paid.
I can not reproduce it on 1.14.4. Can you try [this build](https://github.com/kernitus/BukkitOldCombatMechanics/files/3639872/OCM.zip), enable debug in the config and say what the *yellow numbers* are?
![yellow numbers](https://user-images.githubusercontent.com/20284688/65389948-52eb9500-dd4a-11e9-9454-97d50fcadea6.png).

If you don't want to run some random jar, I will set up a CI job for it, so you can see where the code comes from.

**Comment by ElytraPvP** [comment] 2019-09-22 15:09
haha sure ill give it a go

**Comment by ElytraPvP** [comment] 2019-09-22 15:11
Also i tested it without qrpg and it works its just qrpg thats messing it up :(

**Comment by ElytraPvP** [comment] 2019-09-22 15:21
![image](https://user-images.githubusercontent.com/53577866/65390237-0ce7fe80-dd55-11e9-8255-db59cf9104de.png)
i set the damage in the config to 1 but it does 9 read this. When i dont have qrpg the orange text is 1

**Comment by I-Al-Istannen** [comment] 2019-09-22 15:52
Guess we will need to get in touch with QuantumRPG then...

Is there any option in that plugin to set tool/weapon damage? OCM is trying to play nice and sets the new damage right at the beginning, before other plugins should process the event.
If not, somebody needs to contact the QuantumRPG author and ask him about it.

@kernitus or @Rayzr522 , do you wanna do that? My time is *slightly* limited by ~~impending doom~~ a math exam :)
For you: The golden text is the final damage from a `MONITOR` listener. So *something* alters the event after OCM has done its job, and that something seems to be QuantumRPG. I really gotta finish the event tracer upgrade when I have more time Rayzr :D

**Comment by ElytraPvP** [comment] 2019-09-22 16:03
hmmm it might also be JupiterCore its a dependency

**Comment by ElytraPvP** [comment] 2019-09-22 16:05
Would i be allowed to send a config of a payed plugin so we can give a look into it

**Comment by kernitus** [comment] 2019-09-22 16:37
@ElytraPvP I guess we could have a look if there's any settings that would help

**Comment by ElytraPvP** [comment] 2019-09-22 16:38
Should i just upload it here?

**Comment by Rayzr522** [comment] 2019-09-22 20:56
Yes, or to Pastebin and then paste a link here.

**Comment by ElytraPvP** [comment] 2019-09-23 04:16
Here

**Comment by ElytraPvP** [comment] 2019-09-23 04:18
[config.txt](https://github.com/kernitus/BukkitOldCombatMechanics/files/3640592/config.txt)

**Comment by kernitus** [comment] 2019-09-24 16:33
Well then I'm going to close this issue, if there are any further developements we can always open it again.

**Closed by kernitus** 2019-09-24 16:33 UTC
Labels: incompatibility
